language: java
os:
  - linux
  - osx
env:
  - SBT_VERSION_CMD="++2.10.6"
  - SBT_VERSION_CMD="++2.12.2 ^^1.0.0-M6"
jdk: oraclejdk8
before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install xz;
    fi
script:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      ./sbt "SBT_VERSION_CMD validateOSX" ;
    fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      ./sbt "SBT_VERSION_CMD validateLinux" ;
    fi

addons:
  apt:
    packages:
    - rpm

sudo: false
cache:
 apt: true
 directories:
 - $HOME/.sbt
 - $HOME/.ivy2
